name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@master

  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: errata-ai/vale-action@reviewdog
